# Docker image for TYPO3 CMS
# Copyright (C) 2016-2020  Martin Helmich <martin@helmich.me>
#                          and contributors <https://github.com/martin-helmich/docker-typo3/graphs/contributors>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

version: "3"
services:
  typo3:
    build: .
    ports:
      - "4242:80"
    volumes:
      - ./typo3/fileadmin:/var/www/html/fileadmin
      - ./typo3/typo3conf:/var/www/html/typo3conf
      - ./typo3/uploads:/var/www/html/uploads
      - typo3temp:/var/www/html/typo3temp
    networks:
      - backend
  database:
    image: mysql:8.0
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    environment:
      - "MYSQL_USER=typo3"
      - "MYSQL_PASSWORD=password"
      - "MYSQL_DATABASE=typo3"
      - "MYSQL_ROOT_PASSWORD=password"
    volumes:
      - database:/var/lib/mysql
    networks:
      - backend
volumes:
  database:
  typo3temp:
networks:
  backend:
