imports:
  - { resource: 'EXT:blog/Configuration/Routes/Default.yaml' }
base: /
dependencies:
  - mountain-star/template
  - blog/integration
languages:
  -
    title: English
    enabled: true
    locale: en_US.UTF-8
    hreflang: ''
    base: /
    websiteTitle: ''
    navigationTitle: ''
    flag: global
    languageId: 0
rootPageId: 1
websiteTitle: 'Mountain Star'
