<?php

// autoload_classmap.php @generated by TYPO3

$typo3InstallDir = \TYPO3\CMS\Core\Core\Environment::getPublicPath() . '/';

return array(
    'BK2K\\BootstrapPackage\\' => array($typo3InstallDir . 'typo3conf/ext/bootstrap_package/Classes'),
    'MountainStar\\MountainStarBootstrapTemplate\\' => array($typo3InstallDir . 'typo3conf/ext/mountain_star_bootstrap_template/Classes'),
    'T3G\\AgencyPack\\Blog\\' => array($typo3InstallDir . 'typo3conf/ext/blog/Classes'),
);
